# Generated by Django 4.1.3 on 2023-01-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bend', '0003_prodb'),
    ]

    operations = [
        migrations.CreateModel(
            name='logdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
