# Generated by Django 4.1.3 on 2023-02-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bend', '0004_logdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdb',
            old_name='username',
            new_name='name',
        ),
    ]
