# Generated by Django 4.1.3 on 2023-02-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fend', '0003_prodetaildb'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodetaildb',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
