# Generated by Django 4.1.3 on 2023-02-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fend', '0004_prodetaildb_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prodetaildb',
            new_name='cartdb',
        ),
    ]
